In [1]:
import numpy as np
import pandas as pd
# from pandas import isnull
# from pandas.conftest import dropna
# from pandas.core.common import fill_missing_names

In [21]:
import re
string = "hellow 123 world 456"
#  创建正则表达式
pattern = r"hellow"   #     \d+   匹配一个或多个数字
# 1.match 匹配开始位置 没有匹配成功返回一个空对象  匹配成功返回一个 re.match
match = re.match(pattern, string)
print(match)
# 2. search 匹配整个字符串 但是返回第一个匹配结果
search = re.search(pattern, string)
print(search.group())      #  .group 返回匹配对象
# 3.findall 匹配整个字符串 返回匹配到的结果
pattern = r'\d+'
findall = re.findall(pattern, string)
print(findall)
# 4.split       分割
split = re.split(pattern, string)
print(split)
# 5.sub 替换
sub = re.sub(pattern, "520", string)
print(sub)
string = '2026-10-20'
pattern = r'(\d+)-(\d+)-(\d+)'
match = re.match(pattern, string)
print(match.group())
print(match.group(2))

<re.Match object; span=(0, 6), match='hellow'>
hellow
['123', '456']
['hellow ', ' world ', '']
hellow 520 world 520
2026-10-20
10

In [66]:
# data = pd.read_csv(r'D:\代码学习\pythonProject\python_numpy_learning\二手车之家信息 - 副本.csv')
# print(data.head())
# # print((data.isnull()).sum())
# print(len(data))
# # 检查是否有重复数据
# (data.duplicated()).sum()
# print(data.drop_duplicates())
# (data.价格.str.contains('万')).sum()
# data.价格.map(lambda x: str(x.replace('万','W')))
# data.loc[:,'价格'] = data.价格.map(lambda x: str(x.replace('万','W')))
# data

                          名称  \
0  宝马X1 2018款 sDrive18Li 尊享型
1  宝马X1 2018款 sDrive18Li 尊享型
2  神行者2 2013款 2.0T Si4 SE汽油版
3    奔驰GLA 2018款 GLA 200 时尚型
4    领动 2016款 1.4T 双离合炫动・活力型

                                                  图片      价格     上牌时间    表显里程  \
0  https://2sc2.autoimg.cn/escimg/g1/M06/BB/43/f_...  17.88万  2018/04  7.5万公里
1  https://2sc2.autoimg.cn/escimg/g29/M04/25/23/f...  20.78万  2018/12    2万公里
2  https://2sc2.autoimg.cn/escimg/g1/M08/2C/A5/f_...  17.98万  2014/03    8万公里
3  https://2sc2.autoimg.cn/escimg/g23/M10/7D/42/f...  19.68万  2018/04  3.2万公里
4  https://2sc2.autoimg.cn/escimg/g2/M06/84/F1/f_...   6.98万  2016/12    5万公里

                                                  链接  地区     来源
0  https://www.che168.com/lianmeng/373397/3860551...  合肥  二手车之家
1  https://www.che168.com/lianmeng/188439/3903927...  合肥  二手车之家
2  https://www.che168.com/lianmeng/188439/3914026...  合肥  二手车之家
3  https://www.che168.com/lianmeng/373397/3944995...  合肥  二手车之家
4  https://semnt.autohome.com.cn/monitor?rtype=2&...  合肥  二手车之家
124464
                                            名称  \
0                    宝马X1 2018款 sDrive18Li 尊享型
1                    宝马X1 2018款 sDrive18Li 尊享型
2                    神行者2 2013款 2.0T Si4 SE汽油版
3                      奔驰GLA 2018款 GLA 200 时尚型
4                      领动 2016款 1.4T 双离合炫动・活力型
...                                        ...
124459          奔驰GLE 2020款 GLE 350 4MATIC 时尚型
124460                        揽胜星脉 2019款 250PS
124461                  Macan 2018款 Macan 2.0T
124462          揽胜运动版 2020款 3.0 L6 HSE DYNAMIC
124463  Panamera 2014款 Panamera Executive 3.0T

                                                       图片      价格     上牌时间  \
0       https://2sc2.autoimg.cn/escimg/g1/M06/BB/43/f_...  17.88万  2018/04
1       https://2sc2.autoimg.cn/escimg/g29/M04/25/23/f...  20.78万  2018/12
2       https://2sc2.autoimg.cn/escimg/g1/M08/2C/A5/f_...  17.98万  2014/03
3       https://2sc2.autoimg.cn/escimg/g23/M10/7D/42/f...  19.68万  2018/04
4       https://2sc2.autoimg.cn/escimg/g2/M06/84/F1/f_...   6.98万  2016/12
...                                                   ...     ...      ...
124459  https://x.autoimg.cn/2scimg/pc/web/20160509/de...   72.5万  2019/12
124460  https://x.autoimg.cn/2scimg/pc/web/20160509/de...   44.8万  2019/06
124461  https://x.autoimg.cn/2scimg/pc/web/20160509/de...   55.9万  2019/01
124462  https://x.autoimg.cn/2scimg/pc/web/20160509/de...   88.8万  2019/09
124463  https://x.autoimg.cn/2scimg/pc/web/20160509/de...   75.8万  2016/05

          表显里程                                                 链接  地区     来源
0       7.5万公里  https://www.che168.com/lianmeng/373397/3860551...  合肥  二手车之家
1         2万公里  https://www.che168.com/lianmeng/188439/3903927...  合肥  二手车之家
2         8万公里  https://www.che168.com/lianmeng/188439/3914026...  合肥  二手车之家
3       3.2万公里  https://www.che168.com/lianmeng/373397/3944995...  合肥  二手车之家
4         5万公里  https://semnt.autohome.com.cn/monitor?rtype=2&...  合肥  二手车之家
...        ...                                                ...  ..    ...
124459    3万公里  https://www.che168.com/dealer/239236/39265112....  苏州  二手车之家
124460  1.5万公里  https://www.che168.com/dealer/86324/39517678.h...  苏州  二手车之家
124461  2.1万公里  https://www.che168.com/dealer/86324/38422868.h...  苏州  二手车之家
124462  1.2万公里  https://www.che168.com/dealer/335626/39242776....  苏州  二手车之家
124463  8.7万公里  https://www.che168.com/dealer/335626/39339934....  苏州  二手车之家

[124459 rows x 8 columns]

,名称,图片,价格,上牌时间,表显里程,链接,地区,来源
0,宝马X1 2018款 sDrive18Li 尊享型,https://2sc2.autoimg.cn/escimg/g1/M06/BB/43/f_...,17.88W,2018/04,7.5万公里,https://www.che168.com/lianmeng/373397/3860551...,合肥,二手车之家
1,宝马X1 2018款 sDrive18Li 尊享型,https://2sc2.autoimg.cn/escimg/g29/M04/25/23/f...,20.78W,2018/12,2万公里,https://www.che168.com/lianmeng/188439/3903927...,合肥,二手车之家
2,神行者2 2013款 2.0T Si4 SE汽油版,https://2sc2.autoimg.cn/escimg/g1/M08/2C/A5/f_...,17.98W,2014/03,8万公里,https://www.che168.com/lianmeng/188439/3914026...,合肥,二手车之家
3,奔驰GLA 2018款 GLA 200 时尚型,https://2sc2.autoimg.cn/escimg/g23/M10/7D/42/f...,19.68W,2018/04,3.2万公里,https://www.che168.com/lianmeng/373397/3944995...,合肥,二手车之家
4,领动 2016款 1.4T 双离合炫动・活力型,https://2sc2.autoimg.cn/escimg/g2/M06/84/F1/f_...,6.98W,2016/12,5万公里,https://semnt.autohome.com.cn/monitor?rtype=2&...,合肥,二手车之家
...,...,...,...,...,...,...,...,...
124459,奔驰GLE 2020款 GLE 350 4MATIC 时尚型,https://x.autoimg.cn/2scimg/pc/web/20160509/de...,72.5W,2019/12,3万公里,https://www.che168.com/dealer/239236/39265112....,苏州,二手车之家
124460,揽胜星脉 2019款 250PS,https://x.autoimg.cn/2scimg/pc/web/20160509/de...,44.8W,2019/06,1.5万公里,https://www.che168.com/dealer/86324/39517678.h...,苏州,二手车之家
124461,Macan 2018款 Macan 2.0T,https://x.autoimg.cn/2scimg/pc/web/20160509/de...,55.9W,2019/01,2.1万公里,https://www.che168.com/dealer/86324/38422868.h...,苏州,二手车之家
124462,揽胜运动版 2020款 3.0 L6 HSE DYNAMIC,https://x.autoimg.cn/2scimg/pc/web/20160509/de...,88.8W,2019/09,1.2万公里,https://www.che168.com/dealer/335626/39242776....,苏州,二手车之家
124463,Panamera 2014款 Panamera Executive 3.0T,https://x.autoimg.cn/2scimg/pc/web/20160509/de...,75.8W,2016/05,8.7万公里,https://www.che168.com/dealer/335626/39339934....,苏州,二手车之家

In [47]:
# 矢量化字符串函数
data = {'小红':'971483642@qq.com',
        '小明':'934782623@qq.com',
        '小白':'khjdas@gamil.com',
        '小绿':np.nan
}
ps = pd.Series(data)
print(ps)
print((ps.isnull()))
print(ps.map(lambda x: str(x).split('@')))
# contains  是否包含
print(ps.str.contains('qq'))
print(ps.loc[ps.str.contains('qq', na=False)])
print(ps.str.replace('qq', 'gamil'))
print(ps.str.split('@'))
print(ps.str.get(1))
print(ps.str.len())
print(ps.str.slice(1,5))   #  截取
print(ps.str.extract(r'(\d+)'))
print(ps.str.findall('@'))

小红    971483642@qq.com
小明    934782623@qq.com
小白    khjdas@gamil.com
小绿                 NaN
dtype: str
小红    False
小明    False
小白    False
小绿     True
dtype: bool
小红    [971483642, qq.com]
小明    [934782623, qq.com]
小白    [khjdas, gamil.com]
小绿                  [nan]
dtype: object
小红     True
小明     True
小白    False
小绿    False
dtype: bool
小红    971483642@qq.com
小明    934782623@qq.com
dtype: str
小红    971483642@gamil.com
小明    934782623@gamil.com
小白       khjdas@gamil.com
小绿                    NaN
dtype: str
小红    [971483642, qq.com]
小明    [934782623, qq.com]
小白    [khjdas, gamil.com]
小绿                    NaN
dtype: object
小红      7
小明      3
小白      h
小绿    NaN
dtype: str
小红    16.0
小明    16.0
小白    16.0
小绿     NaN
dtype: float64
小红    7148
小明    3478
小白    hjda
小绿     NaN
dtype: str
            0
小红  971483642
小明  934782623
小白        NaN
小绿        NaN
小红    [@]
小明    [@]
小白    [@]
小绿    NaN
dtype: object

In [ ]:
# 数据清洗总结
# 一.处理缺少数据
# 1.填充或删除
#   检测---isnull
#   删除---dropna
#   填充---fillna
# 二.处理重复数据
# 1.删除
#   检测重复数据---duplicated
#   删除重复数据---dorp_duplicates
# 三.数据类型不统一
# 1.数据类型转换
# 四.部分数据包含数值和字符串
# 1.字符串处理
# 五.部分数据存在异常值
# 1.删除
#   dorp()
# 六.少数数据不利于分析
# 1.替换
#   replace

In [33]:
data1 = pd.read_csv(r'D:\代码学习\pythonProject\python_numpy_learning\车行信息-副本.csv')
# print(data1.shape)
data1.head()
data2 = data1.drop_duplicates()
data2
data2.columns = ['汽车类型','图片','售价','上牌时间','里程','链接','地区','主要来源']
data2
s = data2['汽车类型']
mask = s.str.contains('xxxx')
mask
df = data2.loc[~mask]
df
ds = df['汽车类型']
mas = ds.str.contains('名称')
df1 = df.loc[~mas]
df1
df1['上牌时间'] = pd.to_datetime(df1['上牌时间'],format='%Y/%m')
df1
df1['售价'] = df1.售价.map(lambda x: float(x.replace('万','')))
df1
df1.dropna()

,汽车类型,图片,售价,上牌时间,里程,链接,地区,主要来源
1,宝马X1 2018款 sDrive18Li 尊享型,https://2sc2.autoimg.cn/escimg/g29/M04/25/23/f...,20.78,2018-12-01,2万公里,https://www.che168.com/lianmeng/188439/3903927...,合肥,二手车之家
4,领动 2016款 1.4T 双离合炫动・活力型,https://2sc2.autoimg.cn/escimg/g2/M06/84/F1/f_...,6.98,2016-12-01,5万公里,https://semnt.autohome.com.cn/monitor?rtype=2&...,合肥,二手车之家
6,奔驰S级 2014款 S 320 L 商务型,https://2sc2.autoimg.cn/escimg/g17/M01/CD/A4/f...,59.99,2016-02-01,10.6万公里,https://semnt.autohome.com.cn/monitor?rtype=2&...,合肥,二手车之家
9,奥迪A4L 2020款 40 TFSI 豪华动感型,https://2sc2.autoimg.cn/escimg/g25/M09/0B/80/f...,29.99,2020-10-01,0.41万公里,https://semnt.autohome.com.cn/monitor?rtype=2&...,合肥,二手车之家
10,Macan 2018款 Macan 2.0T,https://2sc2.autoimg.cn/escimg/g26/M05/B8/6A/f...,56.80,2019-06-01,2.7万公里,https://semnt.autohome.com.cn/monitor?rtype=2&...,合肥,二手车之家
12,宝马3系 2018款 320Li 时尚型,https://x.autoimg.cn/2scimg/pc/web/20160509/de...,23.90,2018-01-01,4万公里,https://semnt.autohome.com.cn/monitor?rtype=2&...,合肥,二手车之家
13,欧陆 2010款 Supersports 6.0 敞篷版,https://x.autoimg.cn/2scimg/pc/web/20160509/de...,136.80,2011-03-01,2.8万公里,https://semnt.autohome.com.cn/monitor?rtype=2&...,合肥,二手车之家
16,奔驰CLA 2016款 CLA 220 4MATIC,https://x.autoimg.cn/2scimg/pc/web/20160509/de...,20.70,2016-04-01,4.7万公里,https://semnt.autohome.com.cn/monitor?rtype=2&...,合肥,二手车之家
22,奔驰GLC 2017款 GLC 260 4MATIC 豪华型,https://x.autoimg.cn/2scimg/pc/web/20160509/de...,30.60,2017-05-01,7.8万公里,https://semnt.autohome.com.cn/monitor?rtype=2&...,合肥,二手车之家
23,DS 5 2015款 1.6T 雅致版THP160,https://x.autoimg.cn/2scimg/pc/web/20160509/de...,9.40,2016-04-01,4.9万公里,https://semnt.autohome.com.cn/monitor?rtype=2&...,合肥,二手车之家
24,英菲尼迪Q60 2019款 2.0T 豪华版,https://x.autoimg.cn/2scimg/pc/web/20160509/de...,30.98,2019-01-01,0.97万公里,https://semnt.autohome.com.cn/monitor?rtype=2&...,合肥,二手车之家
27,迈锐宝 2016款 1.6T 自动舒适版,https://x.autoimg.cn/2scimg/pc/web/20160509/de...,7.50,2016-02-01,5万公里,https://semnt.autohome.com.cn/monitor?rtype=2&...,合肥,二手车之家
29,牧马人 2018款 2.0T Sahara 四门版,https://x.autoimg.cn/2scimg/pc/web/20160509/de...,44.58,2019-02-01,3.2万公里,https://semnt.autohome.com.cn/monitor?rtype=2&...,合肥,二手车之家
30,保时捷718 2018款 Boxster 2.0T,https://x.autoimg.cn/2scimg/pc/web/20160509/de...,63.88,2018-06-01,0.6万公里,https://semnt.autohome.com.cn/monitor?rtype=2&...,合肥,二手车之家
31,奥迪A4L 2013款 35 TFSI 自动舒适型,https://x.autoimg.cn/2scimg/pc/web/20160509/de...,14.58,2013-11-01,8.23万公里,https://semnt.autohome.com.cn/monitor?rtype=2&...,合肥,二手车之家
33,奔驰GLE 2016款 GLE 320 4MATIC 豪华型,https://x.autoimg.cn/2scimg/pc/web/20160509/de...,56.80,2018-01-01,3.8万公里,https://semnt.autohome.com.cn/monitor?rtype=2&...,合肥,二手车之家
34,宝马3系 2018款 320Li M运动曜夜版,https://x.autoimg.cn/2scimg/pc/web/20160509/de...,25.88,2018-04-01,7万公里,https://semnt.autohome.com.cn/monitor?rtype=2&...,合肥,二手车之家